### ISSUE TITLE
More general nD rotations

### ISSUE THREAD

**Issue by GPMueller** [NOhs/mgen#7]
The docs say (stress is mine)
> (nD) Give an angle and a pair of **orthogonal** vectors that span a plane

It seems to me that, since orthogonality is checked anyways, the nD vectors could be orthogonalized if necessary. This would generalize the function `rotation_from_angle_and_plane` a little. The remaining requirement would be that the two vectors not be parallel.

**Comment by NOhs** [comment]
That might be a good option.

**Comment by NOhs** [comment]
Seems https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.qr.html might be an easy approach.

**Comment by NOhs** [comment]
Hm, ok maybe not. It seems to not preserve signs, which I have to admit is not too suprising.

**Comment by NOhs** [comment]
Solved by #10
